#!/usr/bin/env python3

import argparse

parser = argparse.ArgumentParser(description='Read a file in reverse')

# positional argument
parser.add_argument('filename', help='the file to read')

# optoinal arguments
parser.add_argument('--limit', '-l', type=int, help='the number of lines to read')
parser.add_argument('--version', '-v', action='version', version='%(prog)s 1.0')

args = parser.parse_args()

try:
	f = open(args.filename)
	limit = args.limit
except FileNotFoundError as err:
	print("Error: " + str(err))
else: 
	with f:
		lines = f.readlines()
		lines.reverse()

		if limit:
			lines = lines[:args.limit]

		for line in lines:
			print(line.strip()[::-1])

